## SVM Machine Learning Model

In [203]:
# Libraries
import matplotlib.pyplot as plt
import pandas as pd
import math
import numpy as np
import datetime as DT
from sklearn import svm
from sklearn import datasets, linear_model


#read file
df1 = pd.read_csv('players11.csv')
df2 = pd.read_csv('players12.csv')
df3 = pd.read_csv('players14.csv')

frames = [df1, df2]
df = pd.concat(frames,ignore_index=True)
df['dob'] = pd.to_datetime(df['dob'], infer_datetime_format=True)    # 1
df['dob'] = df['dob'].where(df['dob'] < now, df['dob'] -  np.timedelta64(100, 'Y'))   # 2
df['age'] = (now - df['dob']).astype('<m8[Y]')    # 3


#Group parameters
df['Tackling'] = df[['SlidingTackle','StandingTackle']].mean(axis=1)
df['Passing'] = df[['LongPassing','ShortPassing']].mean(axis=1)
df['Movement'] = df[['Acceleration','SprintSpeed','Agility']].mean(axis=1)
df = df[(df['club_pos']!='SUB') & (df['club_pos']!='RES')]

bar_df = df
mapp = {'GK': 0,
'CB': 0,
'LCB': 0,
'RCB': 0,
'LB':0,
'RB': 0,
'RWB': 0,
'LWB': 0,
'CM' : 0,
'RM' : 0,
'LDM': 0,
'LAM': 0,
'RDM': 0,
'RAM': 0,
'RCM' : 0,
'LCM' : 0,
'CDM': 0,
'CAM': 0,
'LM' : 0,
'RM' : 0,
'LW': 1,
'RW': 1,
'LF': 1,       
'CF': 1, 
'RF': 1,         
'RS': 1,
'ST': 1,
'LS' : 1}
Ystriker =  df['club_pos'].map(mapp)
Features = df[['Tackling','Interceptions','Passing','BallControl','Dribbling','Movement','Finishing','GKDiving']]
Featuresnp=Features.values

### Feature importance for striker

In [218]:
Ynp=Ystriker.values
clf = svm.SVC(decision_function_shape='ovo',kernel='linear')
clf.fit(Featuresnp, Ynp) 


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovo', degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [205]:
clf.coef_

array([[-0.01349469, -0.01648562, -0.10341999,  0.08046808, -0.06061269,
        -0.01065821,  0.1173136 , -0.01585564]])

### Feature importance for midfielder

In [209]:
mapmid = {'GK': 0,
'CB': 0,
'LCB': 0,
'RCB': 0,
'LB':0,
'RB': 0,
'RWB': 0,
'LWB': 0,
'CM' : 1,
'RM' : 1,
'LDM': 1,
'LAM': 1,
'RDM': 1,
'RAM': 1,
'RCM' : 1,
'LCM' : 1,
'CDM': 1,
'CAM': 1,
'LM' : 1,
'RM' : 1,
'LW': 0,
'RW': 0,
'LF': 0,       
'CF': 0, 
'RF': 0,         
'RS': 0,
'ST': 0,
'LS' : 0}
Ymid =  df['club_pos'].map(mapmid)
Ynp=Ymid.values
clf.fit(Featuresnp, Ynp) 



SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovo', degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [210]:
clf.coef_

array([[-0.04297835,  0.02257575,  0.16942539, -0.09707117,  0.04902088,
        -0.00219137,  0.01975266, -0.0161185 ]])

### Feature importance for defender

In [207]:
mapdef = {'GK': 0,
'CB': 1,
'LCB': 1,
'RCB': 1,
'LB':1,
'RB': 1,
'RWB': 1,
'LWB': 1,
'CM' : 0,
'RM' : 0,
'LDM': 0,
'LAM': 0,
'RDM': 0,
'RAM': 0,
'RCM' : 0,
'LCM' : 0,
'CDM': 0,
'CAM': 0,
'LM' : 0,
'RM' : 0,
'LW': 0,
'RW': 0,
'LF': 0,       
'CF': 0, 
'RF': 0,         
'RS': 0,
'ST': 0,
'LS' : 0}


Ydef =  df['club_pos'].map(mapdef)
Ynp=Ydef.values
clf.fit(Featuresnp, Ynp) 



SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovo', degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [213]:
clf.coef_

array([[ 0.21048475, -0.04507476, -0.15440188, -0.01242488, -0.00282847,
         0.02537567, -0.03979661, -0.03860633]])

### Goalkeeper

In [216]:
mapgk = {'GK': 1,
'CB': 0,
'LCB': 0,
'RCB': 0,
'LB':0,
'RB': 0,
'RWB': 0,
'LWB': 0,
'CM' : 0,
'RM' : 0,
'LDM': 0,
'LAM': 0,
'RDM': 0,
'RAM': 0,
'RCM' : 0,
'LCM' : 0,
'CDM': 0,
'CAM': 0,
'LM' : 0,
'RM' : 0,
'LW': 0,
'RW': 0,
'LF': 0,       
'CF': 0, 
'RF': 0,         
'RS': 0,
'ST': 0,
'LS' : 0}


Ygk =  df['club_pos'].map(mapgk)
Ynp=Ygk.values
clf.fit(Featuresnp, Ynp) 

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovo', degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [217]:
clf.coef_

array([[-0.01735977,  0.00159019,  0.01491757, -0.01052458, -0.00042576,
        -0.00656706, -0.00294418,  0.03825022]])

In [226]:
mapclass = {'GK': 0,
'CB': 1,
'LCB': 1,
'RCB': 1,
'LB':1,
'RB': 1,
'RWB': 1,
'LWB': 1,
'CM' : 2,
'RM' : 2,
'LDM': 2,
'LAM': 2,
'RDM': 2,
'RAM': 2,
'RCM' : 2,
'LCM' : 2,
'CDM': 2,
'CAM': 2,
'LM' : 2,
'RM' : 2,
'LW': 3,
'RW': 3,
'LF': 3,       
'CF': 3, 
'RF': 3,         
'RS': 3,
'ST': 3,
'LS' : 3}


Yclass =  df['club_pos'].map(mapclass)
Ynp=Yclass.values
clf.fit(Featuresnp, Ynp) 


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovo', degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [227]:
clf.coef_

array([[-5.41562501e-02, -7.56194898e-02,  6.67051019e-02,
        -2.63274807e-02, -6.21098158e-03, -8.87167351e-02,
         8.87689015e-02,  7.08441908e-02],
       [-8.94423472e-03,  1.94515751e-04, -4.34270472e-03,
         2.41397031e-04, -2.34023856e-03, -1.06896016e-02,
        -1.98889995e-03,  3.33850791e-02],
       [-5.24385320e-03, -1.71522522e-03,  1.37694123e-02,
         8.71312726e-04, -7.31047627e-03, -4.11292502e-03,
        -1.29790115e-02,  3.16155910e-02],
       [ 1.97826534e-01, -4.54847513e-02, -1.58513483e-01,
        -5.41750562e-03, -4.54965193e-03,  2.35542570e-02,
        -3.89420063e-02,  9.81582116e-04],
       [ 9.13849259e-02,  2.44800914e-02, -3.76030155e-02,
        -1.50272124e-02,  1.01525704e-02,  8.85434213e-03,
        -8.15091602e-02,  7.97115542e-03],
       [ 1.33880765e-02,  1.44476093e-02,  1.08004716e-01,
        -9.21095037e-02,  7.07107099e-02,  1.16338405e-02,
        -1.13668299e-01,  7.61789550e-03]])

In [228]:
clf.predict(Featuresnp[0:10])

array([3, 3, 3, 3, 0, 2, 3, 2, 2, 1])

In [229]:
Ynp[0:10]

array([3, 3, 3, 3, 0, 2, 3, 3, 2, 1])