## SVM Machine Learning Model

Defined a multiclass SVM machine learning model using libraries from sklearn to classify a player into Attacker, Midfielder, Defender and Goalkeeper

In [29]:
# Libraries
import matplotlib.pyplot as plt
import pandas as pd
import math
import numpy as np
import datetime as DT
from sklearn import svm
from sklearn import datasets, linear_model
from dataloader import loader_mlmodel


df=loader_mlmodel()
mapp = {'GK': 0,'CB': 0,'LCB': 0,'RCB': 0,'LB':0,'RB': 0,'RWB': 0,'LWB': 0,'CM' : 0,'RM' : 0,'LDM': 0,'LAM': 0,'RDM': 0,'RAM': 0,'RCM' : 0,'LCM' : 0,'CDM': 0,'CAM': 0,'LM' : 0,'RM' : 0,'LW': 1,'RW': 1,'LF': 1,'CF': 1,'RF': 1,'RS': 1,'ST': 1,'LS' : 1}
Ystriker =  df['club_pos'].map(mapp)
Features = df[['StandingTackle','ShortPassing','Crossing','Positioning','GKHandling','BallControl','Aggression']]
Featuresnp=Features.values

### Feature importance for striker

Here, we used a SVM classifier to classify players into strikers and non-strikers. From this, we can understand which characteristics or traits are essential for a striker

In [30]:
Ynp=Ystriker.values
clf = svm.SVC(decision_function_shape='ovo',kernel='linear')
clf.fit(Featuresnp, Ynp) 


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovo', degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [31]:
clf.coef_

array([[-0.04436076, -0.0791623 , -0.05752685,  0.11641591, -0.01341702,
         0.04674585,  0.0215085 ]])

### Feature importance for midfielder

Here, we used a SVM classifier to classify players into midfielders and non-midfielders. From this, we can understand which characteristics or traits are essential for a midfielder

In [32]:
mapmid = {'GK': 0,'CB': 0,'LCB': 0,'RCB': 0,'LB':0,'RB': 0,'RWB': 0,'LWB': 0,'CM' : 1,'RM' : 1,'LDM': 1,'LAM': 1,'RDM': 1,'RAM': 1,'RCM' : 1,'LCM' : 1,'CDM': 1,'CAM': 1,'LM' : 1,'RM' : 1,'LW': 0,'RW': 0,'LF': 0, 'CF': 0, 'RF': 0,'RS': 0,'ST': 0,'LS': 0}
Ymid =  df['club_pos'].map(mapmid)
Ynp=Ymid.values
clf.fit(Featuresnp, Ynp) 



SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovo', degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [33]:
clf.coef_

array([[-0.00026776,  0.15871445, -0.00199868,  0.01669032, -0.00232154,
        -0.02519966, -0.02986746]])

### Feature importance for defender

Here, we used a SVM classifier to classify players into defenders and non-defenders. From this, we can understand which characteristics or traits are essential for a defender

In [34]:
mapdef = {'GK': 0,'CB': 1,'LCB': 1,'RCB': 1,'LB':1,'RB': 1,'RWB': 1,'LWB': 1,'CM' : 0,'RM' : 0,'LDM': 0,'LAM': 0,'RDM': 0,'RAM': 0,'RCM' : 0,'LCM' : 0,'CDM': 0,'CAM': 0,'LM' : 0,'RM' : 0,'LW': 0,'RW': 0,'LF': 0, 'CF': 0, 'RF': 0,'RS': 0,'ST': 0,'LS' : 0}

Ydef =  df['club_pos'].map(mapdef)
Ynp=Ydef.values
clf.fit(Featuresnp, Ynp) 



SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovo', degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [35]:
clf.coef_

array([[ 0.19173923, -0.20459971,  0.06922768, -0.04811022, -0.0693693 ,
        -0.03813824, -0.02327118]])

### Goalkeeper

Here, we used a SVM classifier to classify players into goalkeepers and non-goalkeepers. From this, we can understand which characteristics or traits are essential for a goalkeeper

In [36]:
mapgk = {'GK': 1,'CB': 0,'LCB': 0,'RCB': 0,'LB':0,'RB': 0,'RWB': 0,'LWB': 0,'CM' : 0,'RM' : 0,'LDM': 0,'LAM': 0,'RDM': 0,'RAM': 0,'RCM' : 0,'LCM' : 0,'CDM': 0,'CAM': 0,'LM' : 0,'RM' : 0,'LW': 0,'RW': 0,'LF': 0,'CF': 0, 'RF': 0,'RS': 0,'ST': 0,'LS' : 0}


Ygk =  df['club_pos'].map(mapgk)
Ynp=Ygk.values
clf.fit(Featuresnp, Ynp) 

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovo', degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [37]:
clf.coef_

array([[-0.00975216,  0.0051531 , -0.00098546, -0.00856469,  0.03420101,
        -0.00683177, -0.00417321]])

### Player classifier

Here we have used SVM classifier to classify players into Attackers, Midfielders, Defenders and Goalkeepers based on their skills and traits

In [38]:
mapclass = {'GK': 0,'CB': 1,'LCB': 1,'RCB': 1,'LB':1,'RB': 1,'RWB': 1,'LWB': 1,'CM' : 2,'RM' : 2,'LDM': 2,'LAM': 2,'RDM': 2,'RAM': 2,'RCM' : 2,'LCM' : 2,'CDM': 2,'CAM': 2,'LM' : 2,'RM' : 2,'LW': 3,'RW': 3,'LF': 3,'CF': 3, 'RF': 3,'RS': 3,'ST': 3,'LS' : 3}
Yclass =  df['club_pos'].map(mapclass)
Ynp=Yclass.values
clf.fit(Featuresnp, Ynp)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovo', degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [39]:
clf.predict(Featuresnp[0:40])

array([3, 3, 3, 3, 0, 2, 3, 3, 2, 1, 3, 1, 3, 0, 0, 2, 2, 3, 0, 2, 3, 2, 3,
       2, 3, 1, 3, 2, 0, 0, 3, 3, 2, 2, 2, 0, 2, 2, 2, 3])

In [40]:
Ynp[0:40]

array([3, 3, 3, 3, 0, 2, 3, 3, 2, 1, 3, 1, 3, 0, 0, 2, 2, 3, 0, 2, 3, 2, 3,
       2, 3, 1, 3, 3, 0, 0, 3, 3, 2, 2, 3, 0, 2, 1, 2, 3])